NAME_FILE_PATH = "Library/name.json"
LIBRARY_FILE_PATH = "Library/library.json"
SPECIFICATION_FILE_PATH = "Library/specification.json"
SCALE_FILE_PATH = "Library/scale.json"
OUTPUT_DIR_PATH = "Output/"
TEMP_DIR_PATH = "Library/temp/"
XDATA_FILE_PATH = TEMP_DIR_PATH + "myXdata.txt"
NPN_IB_DATABASE_FILE_PATH = "Database/Ib_NPN_Database_V2.xls"
PNP_IB_DATABASE_FILE_PATH = "Database/Ib_PNP_Database_V2.xls"

SPEC_TXT_FILE_PATH = "Library/Specification_template.txt"